# Generated by Django 2.2.5 on 2019-10-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_mail', models.EmailField(default='info@gemos.online', max_length=254, null=True)),
                ('to_mail', models.EmailField(default='hamidreza.darabi@hotmail.com', max_length=254, null=True)),
                ('subject', models.CharField(default='Hello Wolrd', max_length=50, null=True)),
                ('address', models.CharField(default='mail.gemos.online', max_length=150, null=True)),
                ('port', models.IntegerField(default='26', null=True)),
                ('user_name', models.CharField(default='info@gemos.online', max_length=150, null=True)),
                ('password', models.CharField(default='Nicola+7', max_length=50, null=True)),
            ],
        ),
    ]
