# Generated by Django 2.2.5 on 2019-10-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_mailsender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailSender',
        ),
    ]
