# Generated by Django 2.2.6 on 2019-10-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_delete_mailsender'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients_email', models.TextField(default='admin@site.com,admin2@site.com', help_text="Please be sure to sepreate emails with ','.")),
                ('subject', models.CharField(default='New contact form', max_length=150)),
                ('from_email', models.EmailField(default='donotreply@site.com', max_length=254)),
            ],
        ),
    ]
