# Generated by Django 2.2.6 on 2019-10-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_emailsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailSettings',
            new_name='EmailSetting',
        ),
    ]
