# Generated by Django 2.2.6 on 2019-10-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20191030_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsetting',
            name='recipients_email',
            field=models.TextField(default='admin@site.com,admin2@site.com', help_text='Please be sure to sepreate emails with ( , ).'),
        ),
    ]
